name: Coverage

on:
  push:
    branches: [ develop ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Verify project
        run: mvn verify
      - name: Generate JaCoCo badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: target/site/jacoco/jacoco.csv
          badges-directory: .github/badges
          generate-coverage-badge: true
          coverage-badge-filename: jacoco-coverage.svg
          generate-branches-badge: true
          branches-badge-filename: jacoco-branches.svg
          generate-summary: true
          summary-filename: jacoco-summary.json
      - name: Log coverage
        run: |
          echo "code coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"
      - name: Commit artifacts
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git config --global user.name "Jacob Lee"
            git config --global user.email "JacobLee23@users.noreply.github.com"
            git add .github/badges
            git commit -m "Autogenerated JaCoCo coverage artifacts"
            git push origin HEAD:${GITHUB_REF_NAME}
          fi
      - name: Upload JaCoco coverage report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/
      - name: Clean project
        run: mvn clean
